export const GET_SEARCHED_TITLES_STARTED = 'GET_SEARCHED_TITLES_STARTED';
export const GET_SEARCHED_TITLES_SUCCESS = 'GET_SEARCHED_TITLES_SUCCESS';
export const GET_SEARCHED_TITLES_FAILURE = 'GET_SEARCHED_TITLES_FAILURE';
