export const CHANGE_TITLE_RATING = 'CHANGE_TITLE_RATING';
export const SET_RATING_STARTED = 'SET_RATING_STARTED';
export const SET_RATING_SUCCESS = 'SET_RATING_SUCCESS';
export const SET_RATING_FAILURE = 'SET_RATING_FAILURE';
export const TOGGLE_FAVORITE_STARTED = 'TOGGLE_FAVORITE_STARTED';
export const TOGGLE_FAVORITE_SUCCESS = 'TOGGLE_FAVORITE_SUCCESS';
export const TOGGLE_FAVORITE_FAILURE = 'TOGGLE_FAVORITE_FAILURE';
